#############################################################################
# Makefile for building: SicilyChan
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  SicilyChan.pro
# Template: app
# Command: /opt/Qt5.3.2/5.3/gcc_64/bin/qmake -spec linux-g++ -o Makefile SicilyChan.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++ -I. -I-I -I/usr/include/python2.7 -I/opt/Qt5.3.2/5.3/gcc_64/include -I/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets -I/opt/Qt5.3.2/5.3/gcc_64/include/QtGui -I/opt/Qt5.3.2/5.3/gcc_64/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt5.3.2/5.3/gcc_64 -Wl,-rpath,/opt/Qt5.3.2/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L /usr/lib/python2.7/ -lpython2.7 -L/opt/Qt5.3.2/5.3/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Qt5.3.2/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Defines.cpp \
		Sicily.cpp \
		main.cpp \
		Trans.cpp moc_Sicily.cpp
OBJECTS       = Defines.o \
		Sicily.o \
		main.o \
		Trans.o \
		moc_Sicily.o
DIST          = /opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/lex.prf \
		SicilyChan.pro Defines.cpp \
		Sicily.cpp \
		main.cpp \
		Trans.cpp
QMAKE_TARGET  = SicilyChan
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SicilyChan


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_Sicily.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SicilyChan.pro /opt/Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/lex.prf \
		SicilyChan.pro \
		/opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Widgets.prl \
		/opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Gui.prl \
		/opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile SicilyChan.pro
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/uic.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.3.2/5.3/gcc_64/mkspecs/features/lex.prf:
SicilyChan.pro:
/opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Widgets.prl:
/opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Gui.prl:
/opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile SicilyChan.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/SicilyChan1.0.0 || mkdir -p .tmp/SicilyChan1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/SicilyChan1.0.0/ && $(COPY_FILE) --parents Sicily.h Defines.h .tmp/SicilyChan1.0.0/ && $(COPY_FILE) --parents Defines.cpp Sicily.cpp main.cpp Trans.cpp .tmp/SicilyChan1.0.0/ && $(COPY_FILE) --parents Sicily.ui .tmp/SicilyChan1.0.0/ && (cd `dirname .tmp/SicilyChan1.0.0` && $(TAR) SicilyChan1.0.0.tar SicilyChan1.0.0 && $(COMPRESS) SicilyChan1.0.0.tar) && $(MOVE) `dirname .tmp/SicilyChan1.0.0`/SicilyChan1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SicilyChan1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_Sicily.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Sicily.cpp
moc_Sicily.cpp: Defines.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QFileDialog \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qfiledialog.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qdialog.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QSharedMemory \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedmemory.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QDesktopWidget \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QMouseEvent \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QClipboard \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qclipboard.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QThread \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qthread.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QBitmap \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qbitmap.h \
		/usr/include/python2.7/Python.h \
		/usr/include/python2.7/patchlevel.h \
		/usr/include/python2.7/pyconfig.h \
		/usr/include/python2.7/pymacconfig.h \
		/usr/include/python2.7/pyport.h \
		/usr/include/python2.7/pymath.h \
		/usr/include/python2.7/pymem.h \
		/usr/include/python2.7/object.h \
		/usr/include/python2.7/objimpl.h \
		/usr/include/python2.7/pydebug.h \
		/usr/include/python2.7/unicodeobject.h \
		/usr/include/python2.7/intobject.h \
		/usr/include/python2.7/boolobject.h \
		/usr/include/python2.7/longobject.h \
		/usr/include/python2.7/floatobject.h \
		/usr/include/python2.7/complexobject.h \
		/usr/include/python2.7/rangeobject.h \
		/usr/include/python2.7/stringobject.h \
		/usr/include/python2.7/memoryobject.h \
		/usr/include/python2.7/bufferobject.h \
		/usr/include/python2.7/bytesobject.h \
		/usr/include/python2.7/bytearrayobject.h \
		/usr/include/python2.7/tupleobject.h \
		/usr/include/python2.7/listobject.h \
		/usr/include/python2.7/dictobject.h \
		/usr/include/python2.7/enumobject.h \
		/usr/include/python2.7/setobject.h \
		/usr/include/python2.7/methodobject.h \
		/usr/include/python2.7/moduleobject.h \
		/usr/include/python2.7/funcobject.h \
		/usr/include/python2.7/classobject.h \
		/usr/include/python2.7/fileobject.h \
		/usr/include/python2.7/cobject.h \
		/usr/include/python2.7/pycapsule.h \
		/usr/include/python2.7/traceback.h \
		/usr/include/python2.7/sliceobject.h \
		/usr/include/python2.7/cellobject.h \
		/usr/include/python2.7/iterobject.h \
		/usr/include/python2.7/genobject.h \
		/usr/include/python2.7/descrobject.h \
		/usr/include/python2.7/warnings.h \
		/usr/include/python2.7/weakrefobject.h \
		/usr/include/python2.7/codecs.h \
		/usr/include/python2.7/pyerrors.h \
		/usr/include/python2.7/pystate.h \
		/usr/include/python2.7/pyarena.h \
		/usr/include/python2.7/modsupport.h \
		/usr/include/python2.7/pythonrun.h \
		/usr/include/python2.7/ceval.h \
		/usr/include/python2.7/sysmodule.h \
		/usr/include/python2.7/intrcheck.h \
		/usr/include/python2.7/import.h \
		/usr/include/python2.7/abstract.h \
		/usr/include/python2.7/compile.h \
		/usr/include/python2.7/code.h \
		/usr/include/python2.7/eval.h \
		/usr/include/python2.7/pyctype.h \
		/usr/include/python2.7/pystrtod.h \
		/usr/include/python2.7/pystrcmp.h \
		/usr/include/python2.7/dtoa.h \
		/usr/include/python2.7/pyfpe.h \
		Sicily.h
	/opt/Qt5.3.2/5.3/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++ -I/home/wkcn/Projects/SicilyChan -I/home/wkcn/Projects/SicilyChan/-I -I/usr/include/python2.7 -I/opt/Qt5.3.2/5.3/gcc_64/include -I/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets -I/opt/Qt5.3.2/5.3/gcc_64/include/QtGui -I/opt/Qt5.3.2/5.3/gcc_64/include/QtCore Sicily.h -o moc_Sicily.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_Sicily.h
compiler_uic_clean:
	-$(DEL_FILE) ui_Sicily.h
ui_Sicily.h: Sicily.ui
	/opt/Qt5.3.2/5.3/gcc_64/bin/uic Sicily.ui -o ui_Sicily.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

Defines.o: Defines.cpp Defines.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QFileDialog \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qfiledialog.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qdialog.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QSharedMemory \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedmemory.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QDesktopWidget \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QMouseEvent \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QClipboard \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qclipboard.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QThread \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qthread.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QBitmap \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qbitmap.h \
		/usr/include/python2.7/Python.h \
		/usr/include/python2.7/patchlevel.h \
		/usr/include/python2.7/pyconfig.h \
		/usr/include/python2.7/pymacconfig.h \
		/usr/include/python2.7/pyport.h \
		/usr/include/python2.7/pymath.h \
		/usr/include/python2.7/pymem.h \
		/usr/include/python2.7/object.h \
		/usr/include/python2.7/objimpl.h \
		/usr/include/python2.7/pydebug.h \
		/usr/include/python2.7/unicodeobject.h \
		/usr/include/python2.7/intobject.h \
		/usr/include/python2.7/boolobject.h \
		/usr/include/python2.7/longobject.h \
		/usr/include/python2.7/floatobject.h \
		/usr/include/python2.7/complexobject.h \
		/usr/include/python2.7/rangeobject.h \
		/usr/include/python2.7/stringobject.h \
		/usr/include/python2.7/memoryobject.h \
		/usr/include/python2.7/bufferobject.h \
		/usr/include/python2.7/bytesobject.h \
		/usr/include/python2.7/bytearrayobject.h \
		/usr/include/python2.7/tupleobject.h \
		/usr/include/python2.7/listobject.h \
		/usr/include/python2.7/dictobject.h \
		/usr/include/python2.7/enumobject.h \
		/usr/include/python2.7/setobject.h \
		/usr/include/python2.7/methodobject.h \
		/usr/include/python2.7/moduleobject.h \
		/usr/include/python2.7/funcobject.h \
		/usr/include/python2.7/classobject.h \
		/usr/include/python2.7/fileobject.h \
		/usr/include/python2.7/cobject.h \
		/usr/include/python2.7/pycapsule.h \
		/usr/include/python2.7/traceback.h \
		/usr/include/python2.7/sliceobject.h \
		/usr/include/python2.7/cellobject.h \
		/usr/include/python2.7/iterobject.h \
		/usr/include/python2.7/genobject.h \
		/usr/include/python2.7/descrobject.h \
		/usr/include/python2.7/warnings.h \
		/usr/include/python2.7/weakrefobject.h \
		/usr/include/python2.7/codecs.h \
		/usr/include/python2.7/pyerrors.h \
		/usr/include/python2.7/pystate.h \
		/usr/include/python2.7/pyarena.h \
		/usr/include/python2.7/modsupport.h \
		/usr/include/python2.7/pythonrun.h \
		/usr/include/python2.7/ceval.h \
		/usr/include/python2.7/sysmodule.h \
		/usr/include/python2.7/intrcheck.h \
		/usr/include/python2.7/import.h \
		/usr/include/python2.7/abstract.h \
		/usr/include/python2.7/compile.h \
		/usr/include/python2.7/code.h \
		/usr/include/python2.7/eval.h \
		/usr/include/python2.7/pyctype.h \
		/usr/include/python2.7/pystrtod.h \
		/usr/include/python2.7/pystrcmp.h \
		/usr/include/python2.7/dtoa.h \
		/usr/include/python2.7/pyfpe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Defines.o Defines.cpp

Sicily.o: Sicily.cpp Sicily.h \
		Defines.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QFileDialog \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qfiledialog.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qdialog.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QSharedMemory \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedmemory.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QDesktopWidget \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QMouseEvent \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QClipboard \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qclipboard.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QThread \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qthread.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QBitmap \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qbitmap.h \
		/usr/include/python2.7/Python.h \
		/usr/include/python2.7/patchlevel.h \
		/usr/include/python2.7/pyconfig.h \
		/usr/include/python2.7/pymacconfig.h \
		/usr/include/python2.7/pyport.h \
		/usr/include/python2.7/pymath.h \
		/usr/include/python2.7/pymem.h \
		/usr/include/python2.7/object.h \
		/usr/include/python2.7/objimpl.h \
		/usr/include/python2.7/pydebug.h \
		/usr/include/python2.7/unicodeobject.h \
		/usr/include/python2.7/intobject.h \
		/usr/include/python2.7/boolobject.h \
		/usr/include/python2.7/longobject.h \
		/usr/include/python2.7/floatobject.h \
		/usr/include/python2.7/complexobject.h \
		/usr/include/python2.7/rangeobject.h \
		/usr/include/python2.7/stringobject.h \
		/usr/include/python2.7/memoryobject.h \
		/usr/include/python2.7/bufferobject.h \
		/usr/include/python2.7/bytesobject.h \
		/usr/include/python2.7/bytearrayobject.h \
		/usr/include/python2.7/tupleobject.h \
		/usr/include/python2.7/listobject.h \
		/usr/include/python2.7/dictobject.h \
		/usr/include/python2.7/enumobject.h \
		/usr/include/python2.7/setobject.h \
		/usr/include/python2.7/methodobject.h \
		/usr/include/python2.7/moduleobject.h \
		/usr/include/python2.7/funcobject.h \
		/usr/include/python2.7/classobject.h \
		/usr/include/python2.7/fileobject.h \
		/usr/include/python2.7/cobject.h \
		/usr/include/python2.7/pycapsule.h \
		/usr/include/python2.7/traceback.h \
		/usr/include/python2.7/sliceobject.h \
		/usr/include/python2.7/cellobject.h \
		/usr/include/python2.7/iterobject.h \
		/usr/include/python2.7/genobject.h \
		/usr/include/python2.7/descrobject.h \
		/usr/include/python2.7/warnings.h \
		/usr/include/python2.7/weakrefobject.h \
		/usr/include/python2.7/codecs.h \
		/usr/include/python2.7/pyerrors.h \
		/usr/include/python2.7/pystate.h \
		/usr/include/python2.7/pyarena.h \
		/usr/include/python2.7/modsupport.h \
		/usr/include/python2.7/pythonrun.h \
		/usr/include/python2.7/ceval.h \
		/usr/include/python2.7/sysmodule.h \
		/usr/include/python2.7/intrcheck.h \
		/usr/include/python2.7/import.h \
		/usr/include/python2.7/abstract.h \
		/usr/include/python2.7/compile.h \
		/usr/include/python2.7/code.h \
		/usr/include/python2.7/eval.h \
		/usr/include/python2.7/pyctype.h \
		/usr/include/python2.7/pystrtod.h \
		/usr/include/python2.7/pystrcmp.h \
		/usr/include/python2.7/dtoa.h \
		/usr/include/python2.7/pyfpe.h \
		ui_Sicily.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QVariant \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QAction \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qaction.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QButtonGroup \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qbuttongroup.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QHeaderView \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qheaderview.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qabstractitemview.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qstyleoption.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qvalidator.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qregularexpression.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qslider.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qabstractslider.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qstyle.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qtabbar.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qrubberband.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Sicily.o Sicily.cpp

main.o: main.cpp Sicily.h \
		Defines.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QFileDialog \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qfiledialog.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qdialog.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QSharedMemory \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedmemory.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QDesktopWidget \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QMouseEvent \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QClipboard \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qclipboard.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QThread \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qthread.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QBitmap \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qbitmap.h \
		/usr/include/python2.7/Python.h \
		/usr/include/python2.7/patchlevel.h \
		/usr/include/python2.7/pyconfig.h \
		/usr/include/python2.7/pymacconfig.h \
		/usr/include/python2.7/pyport.h \
		/usr/include/python2.7/pymath.h \
		/usr/include/python2.7/pymem.h \
		/usr/include/python2.7/object.h \
		/usr/include/python2.7/objimpl.h \
		/usr/include/python2.7/pydebug.h \
		/usr/include/python2.7/unicodeobject.h \
		/usr/include/python2.7/intobject.h \
		/usr/include/python2.7/boolobject.h \
		/usr/include/python2.7/longobject.h \
		/usr/include/python2.7/floatobject.h \
		/usr/include/python2.7/complexobject.h \
		/usr/include/python2.7/rangeobject.h \
		/usr/include/python2.7/stringobject.h \
		/usr/include/python2.7/memoryobject.h \
		/usr/include/python2.7/bufferobject.h \
		/usr/include/python2.7/bytesobject.h \
		/usr/include/python2.7/bytearrayobject.h \
		/usr/include/python2.7/tupleobject.h \
		/usr/include/python2.7/listobject.h \
		/usr/include/python2.7/dictobject.h \
		/usr/include/python2.7/enumobject.h \
		/usr/include/python2.7/setobject.h \
		/usr/include/python2.7/methodobject.h \
		/usr/include/python2.7/moduleobject.h \
		/usr/include/python2.7/funcobject.h \
		/usr/include/python2.7/classobject.h \
		/usr/include/python2.7/fileobject.h \
		/usr/include/python2.7/cobject.h \
		/usr/include/python2.7/pycapsule.h \
		/usr/include/python2.7/traceback.h \
		/usr/include/python2.7/sliceobject.h \
		/usr/include/python2.7/cellobject.h \
		/usr/include/python2.7/iterobject.h \
		/usr/include/python2.7/genobject.h \
		/usr/include/python2.7/descrobject.h \
		/usr/include/python2.7/warnings.h \
		/usr/include/python2.7/weakrefobject.h \
		/usr/include/python2.7/codecs.h \
		/usr/include/python2.7/pyerrors.h \
		/usr/include/python2.7/pystate.h \
		/usr/include/python2.7/pyarena.h \
		/usr/include/python2.7/modsupport.h \
		/usr/include/python2.7/pythonrun.h \
		/usr/include/python2.7/ceval.h \
		/usr/include/python2.7/sysmodule.h \
		/usr/include/python2.7/intrcheck.h \
		/usr/include/python2.7/import.h \
		/usr/include/python2.7/abstract.h \
		/usr/include/python2.7/compile.h \
		/usr/include/python2.7/code.h \
		/usr/include/python2.7/eval.h \
		/usr/include/python2.7/pyctype.h \
		/usr/include/python2.7/pystrtod.h \
		/usr/include/python2.7/pystrcmp.h \
		/usr/include/python2.7/dtoa.h \
		/usr/include/python2.7/pyfpe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Trans.o: Trans.cpp Sicily.h \
		Defines.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QFileDialog \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qfiledialog.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qdialog.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QSharedMemory \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qsharedmemory.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtWidgets/QDesktopWidget \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QMouseEvent \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QClipboard \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qclipboard.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/QThread \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtCore/qthread.h \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/QBitmap \
		/opt/Qt5.3.2/5.3/gcc_64/include/QtGui/qbitmap.h \
		/usr/include/python2.7/Python.h \
		/usr/include/python2.7/patchlevel.h \
		/usr/include/python2.7/pyconfig.h \
		/usr/include/python2.7/pymacconfig.h \
		/usr/include/python2.7/pyport.h \
		/usr/include/python2.7/pymath.h \
		/usr/include/python2.7/pymem.h \
		/usr/include/python2.7/object.h \
		/usr/include/python2.7/objimpl.h \
		/usr/include/python2.7/pydebug.h \
		/usr/include/python2.7/unicodeobject.h \
		/usr/include/python2.7/intobject.h \
		/usr/include/python2.7/boolobject.h \
		/usr/include/python2.7/longobject.h \
		/usr/include/python2.7/floatobject.h \
		/usr/include/python2.7/complexobject.h \
		/usr/include/python2.7/rangeobject.h \
		/usr/include/python2.7/stringobject.h \
		/usr/include/python2.7/memoryobject.h \
		/usr/include/python2.7/bufferobject.h \
		/usr/include/python2.7/bytesobject.h \
		/usr/include/python2.7/bytearrayobject.h \
		/usr/include/python2.7/tupleobject.h \
		/usr/include/python2.7/listobject.h \
		/usr/include/python2.7/dictobject.h \
		/usr/include/python2.7/enumobject.h \
		/usr/include/python2.7/setobject.h \
		/usr/include/python2.7/methodobject.h \
		/usr/include/python2.7/moduleobject.h \
		/usr/include/python2.7/funcobject.h \
		/usr/include/python2.7/classobject.h \
		/usr/include/python2.7/fileobject.h \
		/usr/include/python2.7/cobject.h \
		/usr/include/python2.7/pycapsule.h \
		/usr/include/python2.7/traceback.h \
		/usr/include/python2.7/sliceobject.h \
		/usr/include/python2.7/cellobject.h \
		/usr/include/python2.7/iterobject.h \
		/usr/include/python2.7/genobject.h \
		/usr/include/python2.7/descrobject.h \
		/usr/include/python2.7/warnings.h \
		/usr/include/python2.7/weakrefobject.h \
		/usr/include/python2.7/codecs.h \
		/usr/include/python2.7/pyerrors.h \
		/usr/include/python2.7/pystate.h \
		/usr/include/python2.7/pyarena.h \
		/usr/include/python2.7/modsupport.h \
		/usr/include/python2.7/pythonrun.h \
		/usr/include/python2.7/ceval.h \
		/usr/include/python2.7/sysmodule.h \
		/usr/include/python2.7/intrcheck.h \
		/usr/include/python2.7/import.h \
		/usr/include/python2.7/abstract.h \
		/usr/include/python2.7/compile.h \
		/usr/include/python2.7/code.h \
		/usr/include/python2.7/eval.h \
		/usr/include/python2.7/pyctype.h \
		/usr/include/python2.7/pystrtod.h \
		/usr/include/python2.7/pystrcmp.h \
		/usr/include/python2.7/dtoa.h \
		/usr/include/python2.7/pyfpe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Trans.o Trans.cpp

moc_Sicily.o: moc_Sicily.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Sicily.o moc_Sicily.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

